name       : libkolabxml
version    : 1.1.6
release    : 5
source     :
    - https://mirror.kolabenterprise.com/pub/releases/libkolabxml-1.1.6.tar.gz : e48d7f5de1860a381da27981f6c70de1c9f38c4cd536bc6558b6529ce95f0677
license    :
    - Apache-2.0
    - LGPL-3.0
component  : programming.library
summary    : Kolab XML Format Schema Definitions Library
description: |
    Kolab XML Format Schema Definitions Library.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(xerces-c)
    - libboost-devel
    - swig
    - xsd-devel
setup      : |
    %cmake -DBUILD_TESTS=FALSE \
        -DLIB_SUFFIX=%LIBSUFFIX% .
build      : |
    %make
install    : |
    %make_install
